In [11]:
!pip install contractions

Requirement already satisfied: contractions in /usr/local/lib/python3.11/dist-packages (0.1.73)
Requirement already satisfied: textsearch>=0.0.21 in /usr/local/lib/python3.11/dist-packages (from contractions) (0.0.24)
Requirement already satisfied: anyascii in /usr/local/lib/python3.11/dist-packages (from textsearch>=0.0.21->contractions) (0.3.2)
Requirement already satisfied: pyahocorasick in /usr/local/lib/python3.11/dist-packages (from textsearch>=0.0.21->contractions) (2.2.0)

In [21]:
!pip install gensim

Collecting gensim
  Downloading gensim-4.3.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.1 kB)
Collecting numpy<2.0,>=1.18.5 (from gensim)
  Downloading numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (61 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.0/61.0 kB 2.1 MB/s eta 0:00:00
Collecting scipy<1.14.0,>=1.7.0 (from gensim)
  Downloading scipy-1.13.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (60 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.6/60.6 kB 2.1 MB/s eta 0:00:00
Requirement already satisfied: smart-open>=1.8.1 in /usr/local/lib/python3.11/dist-packages (from gensim) (7.1.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.11/dist-packages (from smart-open>=1.8.1->gensim) (1.17.2)
Downloading gensim-4.3.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (26.7 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.7/26.7 MB 24.2 MB/s eta 0:00:00
Downloading numpy-1.26.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.3/18.3 MB 32.5 MB/s eta 0:00:00
Downloading scipy-1.13.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (38.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 38.6/38.6 MB 8.9 MB/s eta 0:00:00
Installing collected packages: numpy, scipy, gensim
  Attempting uninstall: numpy
    Found existing installation: numpy 2.0.2
    Uninstalling numpy-2.0.2:
      Successfully uninstalled numpy-2.0.2
  Attempting uninstall: scipy
    Found existing installation: scipy 1.15.3
    Uninstalling scipy-1.15.3:
      Successfully uninstalled scipy-1.15.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tsfresh 0.21.0 requires scipy>=1.14.0; python_version >= "3.10", but you have scipy 1.13.1 which is incompatible.
thinc 8.3.6 requires numpy<3.0.0,>=2.0.0, but you have numpy 1.26.4 which is incompatible.
Successfully installed gensim-4.3.3 numpy-1.26.4 scipy-1.13.1

In [1]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("crowdflower/twitter-airline-sentiment")

print("Path to dataset files:", path)

Path to dataset files: /kaggle/input/twitter-airline-sentiment

In [2]:
import pandas as pd
import nltk
import numpy as np

In [3]:
nltk.download('all')

[nltk_data] Downloading collection 'all'
[nltk_data]    |
[nltk_data]    | Downloading package abc to /root/nltk_data...
[nltk_data]    |   Package abc is already up-to-date!
[nltk_data]    | Downloading package alpino to /root/nltk_data...
[nltk_data]    |   Package alpino is already up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_eng to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_eng is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_ru to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_ru is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package averaged_perceptron_tagger_rus to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package averaged_perceptron_tagger_rus is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package basque_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package basque_grammars is already up-to-date!
[nltk_data]    | Downloading package bcp47 to /root/nltk_data...
[nltk_data]    |   Package bcp47 is already up-to-date!
[nltk_data]    | Downloading package biocreative_ppi to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package biocreative_ppi is already up-to-date!
[nltk_data]    | Downloading package bllip_wsj_no_aux to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package bllip_wsj_no_aux is already up-to-date!
[nltk_data]    | Downloading package book_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package book_grammars is already up-to-date!
[nltk_data]    | Downloading package brown to /root/nltk_data...
[nltk_data]    |   Package brown is already up-to-date!
[nltk_data]    | Downloading package brown_tei to /root/nltk_data...
[nltk_data]    |   Package brown_tei is already up-to-date!
[nltk_data]    | Downloading package cess_cat to /root/nltk_data...
[nltk_data]    |   Package cess_cat is already up-to-date!
[nltk_data]    | Downloading package cess_esp to /root/nltk_data...
[nltk_data]    |   Package cess_esp is already up-to-date!
[nltk_data]    | Downloading package chat80 to /root/nltk_data...
[nltk_data]    |   Package chat80 is already up-to-date!
[nltk_data]    | Downloading package city_database to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package city_database is already up-to-date!
[nltk_data]    | Downloading package cmudict to /root/nltk_data...
[nltk_data]    |   Package cmudict is already up-to-date!
[nltk_data]    | Downloading package comparative_sentences to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package comparative_sentences is already up-to-
[nltk_data]    |       date!
[nltk_data]    | Downloading package comtrans to /root/nltk_data...
[nltk_data]    |   Package comtrans is already up-to-date!
[nltk_data]    | Downloading package conll2000 to /root/nltk_data...
[nltk_data]    |   Package conll2000 is already up-to-date!
[nltk_data]    | Downloading package conll2002 to /root/nltk_data...
[nltk_data]    |   Package conll2002 is already up-to-date!
[nltk_data]    | Downloading package conll2007 to /root/nltk_data...
[nltk_data]    |   Package conll2007 is already up-to-date!
[nltk_data]    | Downloading package crubadan to /root/nltk_data...
[nltk_data]    |   Package crubadan is already up-to-date!
[nltk_data]    | Downloading package dependency_treebank to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package dependency_treebank is already up-to-date!
[nltk_data]    | Downloading package dolch to /root/nltk_data...
[nltk_data]    |   Package dolch is already up-to-date!
[nltk_data]    | Downloading package english_wordnet to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package english_wordnet is already up-to-date!
[nltk_data]    | Downloading package europarl_raw to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package europarl_raw is already up-to-date!
[nltk_data]    | Downloading package extended_omw to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package extended_omw is already up-to-date!
[nltk_data]    | Downloading package floresta to /root/nltk_data...
[nltk_data]    |   Package floresta is already up-to-date!
[nltk_data]    | Downloading package framenet_v15 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package framenet_v15 is already up-to-date!
[nltk_data]    | Downloading package framenet_v17 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package framenet_v17 is already up-to-date!
[nltk_data]    | Downloading package gazetteers to /root/nltk_data...
[nltk_data]    |   Package gazetteers is already up-to-date!
[nltk_data]    | Downloading package genesis to /root/nltk_data...
[nltk_data]    |   Package genesis is already up-to-date!
[nltk_data]    | Downloading package gutenberg to /root/nltk_data...
[nltk_data]    |   Package gutenberg is already up-to-date!
[nltk_data]    | Downloading package ieer to /root/nltk_data...
[nltk_data]    |   Package ieer is already up-to-date!
[nltk_data]    | Downloading package inaugural to /root/nltk_data...
[nltk_data]    |   Package inaugural is already up-to-date!
[nltk_data]    | Downloading package indian to /root/nltk_data...
[nltk_data]    |   Package indian is already up-to-date!
[nltk_data]    | Downloading package jeita to /root/nltk_data...
[nltk_data]    |   Package jeita is already up-to-date!
[nltk_data]    | Downloading package kimmo to /root/nltk_data...
[nltk_data]    |   Package kimmo is already up-to-date!
[nltk_data]    | Downloading package knbc to /root/nltk_data...
[nltk_data]    |   Package knbc is already up-to-date!
[nltk_data]    | Downloading package large_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package large_grammars is already up-to-date!
[nltk_data]    | Downloading package lin_thesaurus to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package lin_thesaurus is already up-to-date!
[nltk_data]    | Downloading package mac_morpho to /root/nltk_data...
[nltk_data]    |   Package mac_morpho is already up-to-date!
[nltk_data]    | Downloading package machado to /root/nltk_data...
[nltk_data]    |   Package machado is already up-to-date!
[nltk_data]    | Downloading package masc_tagged to /root/nltk_data...
[nltk_data]    |   Package masc_tagged is already up-to-date!
[nltk_data]    | Downloading package maxent_ne_chunker to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package maxent_ne_chunker is already up-to-date!
[nltk_data]    | Downloading package maxent_ne_chunker_tab to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package maxent_ne_chunker_tab is already up-to-
[nltk_data]    |       date!
[nltk_data]    | Downloading package maxent_treebank_pos_tagger to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package maxent_treebank_pos_tagger is already up-
[nltk_data]    |       to-date!
[nltk_data]    | Downloading package maxent_treebank_pos_tagger_tab to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package maxent_treebank_pos_tagger_tab is already
[nltk_data]    |       up-to-date!
[nltk_data]    | Downloading package moses_sample to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package moses_sample is already up-to-date!
[nltk_data]    | Downloading package movie_reviews to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package movie_reviews is already up-to-date!
[nltk_data]    | Downloading package mte_teip5 to /root/nltk_data...
[nltk_data]    |   Package mte_teip5 is already up-to-date!
[nltk_data]    | Downloading package mwa_ppdb to /root/nltk_data...
[nltk_data]    |   Package mwa_ppdb is already up-to-date!
[nltk_data]    | Downloading package names to /root/nltk_data...
[nltk_data]    |   Package names is already up-to-date!
[nltk_data]    | Downloading package nombank.1.0 to /root/nltk_data...
[nltk_data]    |   Package nombank.1.0 is already up-to-date!
[nltk_data]    | Downloading package nonbreaking_prefixes to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package nonbreaking_prefixes is already up-to-date!
[nltk_data]    | Downloading package nps_chat to /root/nltk_data...
[nltk_data]    |   Package nps_chat is already up-to-date!
[nltk_data]    | Downloading package omw to /root/nltk_data...
[nltk_data]    |   Package omw is already up-to-date!
[nltk_data]    | Downloading package omw-1.4 to /root/nltk_data...
[nltk_data]    |   Package omw-1.4 is already up-to-date!
[nltk_data]    | Downloading package opinion_lexicon to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package opinion_lexicon is already up-to-date!
[nltk_data]    | Downloading package panlex_swadesh to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package panlex_swadesh is already up-to-date!
[nltk_data]    | Downloading package paradigms to /root/nltk_data...
[nltk_data]    |   Package paradigms is already up-to-date!
[nltk_data]    | Downloading package pe08 to /root/nltk_data...
[nltk_data]    |   Package pe08 is already up-to-date!
[nltk_data]    | Downloading package perluniprops to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package perluniprops is already up-to-date!
[nltk_data]    | Downloading package pil to /root/nltk_data...
[nltk_data]    |   Package pil is already up-to-date!
[nltk_data]    | Downloading package pl196x to /root/nltk_data...
[nltk_data]    |   Package pl196x is already up-to-date!
[nltk_data]    | Downloading package porter_test to /root/nltk_data...
[nltk_data]    |   Package porter_test is already up-to-date!
[nltk_data]    | Downloading package ppattach to /root/nltk_data...
[nltk_data]    |   Package ppattach is already up-to-date!
[nltk_data]    | Downloading package problem_reports to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package problem_reports is already up-to-date!
[nltk_data]    | Downloading package product_reviews_1 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package product_reviews_1 is already up-to-date!
[nltk_data]    | Downloading package product_reviews_2 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package product_reviews_2 is already up-to-date!
[nltk_data]    | Downloading package propbank to /root/nltk_data...
[nltk_data]    |   Package propbank is already up-to-date!
[nltk_data]    | Downloading package pros_cons to /root/nltk_data...
[nltk_data]    |   Package pros_cons is already up-to-date!
[nltk_data]    | Downloading package ptb to /root/nltk_data...
[nltk_data]    |   Package ptb is already up-to-date!
[nltk_data]    | Downloading package punkt to /root/nltk_data...
[nltk_data]    |   Package punkt is already up-to-date!
[nltk_data]    | Downloading package punkt_tab to /root/nltk_data...
[nltk_data]    |   Package punkt_tab is already up-to-date!
[nltk_data]    | Downloading package qc to /root/nltk_data...
[nltk_data]    |   Package qc is already up-to-date!
[nltk_data]    | Downloading package reuters to /root/nltk_data...
[nltk_data]    |   Package reuters is already up-to-date!
[nltk_data]    | Downloading package rslp to /root/nltk_data...
[nltk_data]    |   Package rslp is already up-to-date!
[nltk_data]    | Downloading package rte to /root/nltk_data...
[nltk_data]    |   Package rte is already up-to-date!
[nltk_data]    | Downloading package sample_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package sample_grammars is already up-to-date!
[nltk_data]    | Downloading package semcor to /root/nltk_data...
[nltk_data]    |   Package semcor is already up-to-date!
[nltk_data]    | Downloading package senseval to /root/nltk_data...
[nltk_data]    |   Package senseval is already up-to-date!
[nltk_data]    | Downloading package sentence_polarity to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package sentence_polarity is already up-to-date!
[nltk_data]    | Downloading package sentiwordnet to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package sentiwordnet is already up-to-date!
[nltk_data]    | Downloading package shakespeare to /root/nltk_data...
[nltk_data]    |   Package shakespeare is already up-to-date!
[nltk_data]    | Downloading package sinica_treebank to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package sinica_treebank is already up-to-date!
[nltk_data]    | Downloading package smultron to /root/nltk_data...
[nltk_data]    |   Package smultron is already up-to-date!
[nltk_data]    | Downloading package snowball_data to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package snowball_data is already up-to-date!
[nltk_data]    | Downloading package spanish_grammars to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package spanish_grammars is already up-to-date!
[nltk_data]    | Downloading package state_union to /root/nltk_data...
[nltk_data]    |   Package state_union is already up-to-date!
[nltk_data]    | Downloading package stopwords to /root/nltk_data...
[nltk_data]    |   Package stopwords is already up-to-date!
[nltk_data]    | Downloading package subjectivity to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package subjectivity is already up-to-date!
[nltk_data]    | Downloading package swadesh to /root/nltk_data...
[nltk_data]    |   Package swadesh is already up-to-date!
[nltk_data]    | Downloading package switchboard to /root/nltk_data...
[nltk_data]    |   Package switchboard is already up-to-date!
[nltk_data]    | Downloading package tagsets to /root/nltk_data...
[nltk_data]    |   Package tagsets is already up-to-date!
[nltk_data]    | Downloading package tagsets_json to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package tagsets_json is already up-to-date!
[nltk_data]    | Downloading package timit to /root/nltk_data...
[nltk_data]    |   Package timit is already up-to-date!
[nltk_data]    | Downloading package toolbox to /root/nltk_data...
[nltk_data]    |   Package toolbox is already up-to-date!
[nltk_data]    | Downloading package treebank to /root/nltk_data...
[nltk_data]    |   Package treebank is already up-to-date!
[nltk_data]    | Downloading package twitter_samples to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package twitter_samples is already up-to-date!
[nltk_data]    | Downloading package udhr to /root/nltk_data...
[nltk_data]    |   Package udhr is already up-to-date!
[nltk_data]    | Downloading package udhr2 to /root/nltk_data...
[nltk_data]    |   Package udhr2 is already up-to-date!
[nltk_data]    | Downloading package unicode_samples to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package unicode_samples is already up-to-date!
[nltk_data]    | Downloading package universal_tagset to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package universal_tagset is already up-to-date!
[nltk_data]    | Downloading package universal_treebanks_v20 to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package universal_treebanks_v20 is already up-to-
[nltk_data]    |       date!
[nltk_data]    | Downloading package vader_lexicon to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package vader_lexicon is already up-to-date!
[nltk_data]    | Downloading package verbnet to /root/nltk_data...
[nltk_data]    |   Package verbnet is already up-to-date!
[nltk_data]    | Downloading package verbnet3 to /root/nltk_data...
[nltk_data]    |   Package verbnet3 is already up-to-date!
[nltk_data]    | Downloading package webtext to /root/nltk_data...
[nltk_data]    |   Package webtext is already up-to-date!
[nltk_data]    | Downloading package wmt15_eval to /root/nltk_data...
[nltk_data]    |   Package wmt15_eval is already up-to-date!
[nltk_data]    | Downloading package word2vec_sample to
[nltk_data]    |     /root/nltk_data...
[nltk_data]    |   Package word2vec_sample is already up-to-date!
[nltk_data]    | Downloading package wordnet to /root/nltk_data...
[nltk_data]    |   Package wordnet is already up-to-date!
[nltk_data]    | Downloading package wordnet2021 to /root/nltk_data...
[nltk_data]    |   Package wordnet2021 is already up-to-date!
[nltk_data]    | Downloading package wordnet2022 to /root/nltk_data...
[nltk_data]    |   Package wordnet2022 is already up-to-date!
[nltk_data]    | Downloading package wordnet31 to /root/nltk_data...
[nltk_data]    |   Package wordnet31 is already up-to-date!
[nltk_data]    | Downloading package wordnet_ic to /root/nltk_data...
[nltk_data]    |   Package wordnet_ic is already up-to-date!
[nltk_data]    | Downloading package words to /root/nltk_data...
[nltk_data]    |   Package words is already up-to-date!
[nltk_data]    | Downloading package ycoe to /root/nltk_data...
[nltk_data]    |   Package ycoe is already up-to-date!
[nltk_data]    |
[nltk_data]  Done downloading collection all

True

In [22]:
df = pd.read_csv('/kaggle/input/twitter-airline-sentiment/Tweets.csv')

In [23]:
df.head()

,tweet_id,airline_sentiment,airline_sentiment_confidence,negativereason,negativereason_confidence,airline,airline_sentiment_gold,name,negativereason_gold,retweet_count,text,tweet_coord,tweet_created,tweet_location,user_timezone
0,570306133677760513,neutral,1.0000,NaN,NaN,Virgin America,NaN,cairdin,NaN,0,@VirginAmerica What @dhepburn said.,NaN,2015-02-24 11:35:52 -0800,NaN,Eastern Time (US & Canada)
1,570301130888122368,positive,0.3486,NaN,0.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica plus you've added commercials t...,NaN,2015-02-24 11:15:59 -0800,NaN,Pacific Time (US & Canada)
2,570301083672813571,neutral,0.6837,NaN,NaN,Virgin America,NaN,yvonnalynn,NaN,0,@VirginAmerica I didn't today... Must mean I n...,NaN,2015-02-24 11:15:48 -0800,Lets Play,Central Time (US & Canada)
3,570301031407624196,negative,1.0000,Bad Flight,0.7033,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica it's really aggressive to blast...,NaN,2015-02-24 11:15:36 -0800,NaN,Pacific Time (US & Canada)
4,570300817074462722,negative,1.0000,Can't Tell,1.0000,Virgin America,NaN,jnardino,NaN,0,@VirginAmerica and it's a really big bad thing...,NaN,2015-02-24 11:14:45 -0800,NaN,Pacific Time (US & Canada)

In [24]:
df.groupby('airline')['airline_sentiment'].value_counts()

airline         airline_sentiment
American        negative             1960
                neutral               463
                positive              336
Delta           negative              955
                neutral               723
                positive              544
Southwest       negative             1186
                neutral               664
                positive              570
US Airways      negative             2263
                neutral               381
                positive              269
United          negative             2633
                neutral               697
                positive              492
Virgin America  negative              181
                neutral               171
                positive              152
Name: count, dtype: int64

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14640 entries, 0 to 14639
Data columns (total 15 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   tweet_id                      14640 non-null  int64
 1   airline_sentiment             14640 non-null  object
 2   airline_sentiment_confidence  14640 non-null  float64
 3   negativereason                9178 non-null   object
 4   negativereason_confidence     10522 non-null  float64
 5   airline                       14640 non-null  object
 6   airline_sentiment_gold        40 non-null     object
 7   name                          14640 non-null  object
 8   negativereason_gold           32 non-null     object
 9   retweet_count                 14640 non-null  int64
 10  text                          14640 non-null  object
 11  tweet_coord                   1019 non-null   object
 12  tweet_created                 14640 non-null  object
 13  tweet_location                9907 non-null   object
 14  user_timezone                 9820 non-null   object
dtypes: float64(2), int64(2), object(11)
memory usage: 1.7+ MB

In [26]:
null_counts = df.isnull().sum()
null_percentages = (null_counts / len(df)) * 100

# Display columns with their null percentages
display(pd.DataFrame({'Null Count': null_counts, 'Null Percentage (%)': null_percentages}).sort_values(by='Null Percentage (%)', ascending=False))

                              Null Count  Null Percentage (%)
negativereason_gold                14608            99.781421
airline_sentiment_gold             14600            99.726776
tweet_coord                        13621            93.039617
negativereason                      5462            37.308743
user_timezone                       4820            32.923497
tweet_location                      4733            32.329235
negativereason_confidence           4118            28.128415
tweet_id                               0             0.000000
airline_sentiment                      0             0.000000
airline_sentiment_confidence           0             0.000000
airline                                0             0.000000
name                                   0             0.000000
retweet_count                          0             0.000000
text                                   0             0.000000
tweet_created                          0             0.000000

In [27]:
df = df[['text', 'airline_sentiment']]
df

                                                    text airline_sentiment
0                    @VirginAmerica What @dhepburn said.           neutral
1      @VirginAmerica plus you've added commercials t...          positive
2      @VirginAmerica I didn't today... Must mean I n...           neutral
3      @VirginAmerica it's really aggressive to blast...          negative
4      @VirginAmerica and it's a really big bad thing...          negative
...                                                  ...               ...
14635  @AmericanAir thank you we got on a different f...          positive
14636  @AmericanAir leaving over 20 minutes Late Flig...          negative
14637  @AmericanAir Please bring American Airlines to...           neutral
14638  @AmericanAir you have my money, you change my ...          negative
14639  @AmericanAir we have 8 ppl so we need 2 know h...           neutral

[14640 rows x 2 columns]

In [12]:
from nltk import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.stem import PorterStemmer
from nltk import sent_tokenize
import contractions
import re
import string

In [15]:
lemmatizer = WordNetLemmatizer()

def clean_text(text):
    text = contractions.fix(text)
    text = re.sub(r"http\S+|www.\S+", "", text)
    text = re.sub(r"@\w+", "", text)
    text = re.sub(r"#\w+", "", text)
    text = text.translate(str.maketrans('', '', string.punctuation))

    text = re.sub(r'[^\w\s]', '', text)
    text = re.sub(r'[^\x00-\x7F]+', '', text)

    tokens = nltk.word_tokenize(text.lower())
    lemmatized = [lemmatizer.lemmatize(token) for token in tokens]

    return lemmatized

In [28]:
df['text'] = df['text'].apply(lambda x: clean_text(x))
df

                                                    text airline_sentiment
0                                           [what, said]           neutral
1      [plus, you, have, added, commercial, to, the, ...          positive
2      [i, did, not, today, must, mean, i, need, to, ...           neutral
3      [it, is, really, aggressive, to, blast, obnoxi...          negative
4      [and, it, is, a, really, big, bad, thing, abou...          negative
...                                                  ...               ...
14635  [thank, you, we, got, on, a, different, flight...          positive
14636  [leaving, over, 20, minute, late, flight, no, ...          negative
14637             [please, bring, american, airline, to]           neutral
14638  [you, have, my, money, you, change, my, flight...          negative
14639  [we, have, 8, people, so, we, need, 2, know, h...           neutral

[14640 rows x 2 columns]

In [17]:
import gensim.downloader as api
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [18]:
model = api.load('word2vec-google-news-300')

[==================================================] 100.0% 1662.8/1662.8MB downloaded

In [19]:
def avg_word2vec(arr, model):
    valid_vectors = [model[word] for word in arr if word in model]

    if not valid_vectors:
        return np.zeros(model.vector_size)

    return np.mean(valid_vectors, axis=0)

In [ ]:
df['text'] = df['text'].apply(lambda x: avg_word2vec(x, model))

In [30]:
df.loc[14,'text']

array([-9.27734375e-02,  8.10546875e-02, -1.00097656e-01,  2.07031250e-01,
        1.72119141e-02, -1.02050781e-01,  1.18164062e-01, -1.92382812e-01,
       -2.53906250e-02,  1.17187500e-01, -2.42919922e-02, -4.73022461e-03,
       -1.48437500e-01,  2.28271484e-02,  1.08398438e-01,  4.45556641e-03,
        4.57031250e-01,  1.66015625e-01,  1.37695312e-01,  1.33789062e-01,
        1.38671875e-01,  1.82617188e-01,  2.45117188e-01, -1.77734375e-01,
        1.90429688e-01, -1.50390625e-01, -6.10351562e-03,  6.83593750e-02,
       -5.09643555e-03,  4.78515625e-02,  4.73632812e-02, -1.62109375e-01,
       -1.33789062e-01,  2.63671875e-01,  1.17187500e-01,  1.90734863e-03,
       -1.90429688e-02, -8.30078125e-02,  1.15234375e-01,  2.07031250e-01,
        2.46093750e-01,  2.91748047e-02, -8.48388672e-03,  2.45117188e-01,
        3.35937500e-01, -1.73828125e-01, -7.47070312e-02, -2.79541016e-02,
        1.78710938e-01, -4.39453125e-02,  6.46972656e-03, -1.60156250e-01,
        1.68945312e-01,  1.49414062e-01, -1.03515625e-01,  1.21582031e-01,
       -1.04492188e-01,  2.55859375e-01,  1.50146484e-02, -1.67968750e-01,
       -2.40234375e-01,  1.48925781e-02, -2.24609375e-01, -1.13281250e-01,
        1.01928711e-02,  3.39355469e-02, -1.00097656e-01,  7.37304688e-02,
       -1.92382812e-01,  1.08398438e-01,  1.11328125e-01, -8.83789062e-02,
        6.49414062e-02,  1.12304688e-01, -1.50146484e-02,  9.82666016e-03,
        2.14843750e-01,  5.34667969e-02, -1.32812500e-01,  3.80859375e-02,
       -2.79296875e-01,  4.27246094e-02,  1.04003906e-01, -1.00097656e-01,
       -1.04980469e-01, -1.22558594e-01, -2.02148438e-01, -7.66601562e-02,
       -8.34960938e-02, -1.29882812e-01, -1.36108398e-02,  3.58886719e-02,
        4.93164062e-02,  4.68750000e-02, -2.88085938e-02, -5.00488281e-02,
       -4.31640625e-01,  1.15234375e-01,  7.08007812e-02,  2.52685547e-02,
       -1.11328125e-01, -7.32421875e-02,  2.53906250e-02,  5.00488281e-03,
       -8.05664062e-02, -1.87500000e-01, -1.57226562e-01, -6.92749023e-03,
       -3.78417969e-02, -5.43212891e-03, -9.81445312e-02,  3.80859375e-02,
       -1.15234375e-01,  6.68945312e-02,  4.66308594e-02,  1.61132812e-02,
       -1.34887695e-02,  1.64794922e-02, -1.97753906e-02,  2.17773438e-01,
       -1.22680664e-02,  5.66406250e-02, -2.02148438e-01,  1.03515625e-01,
        9.03320312e-02,  4.41894531e-02, -1.04492188e-01, -2.20703125e-01,
        9.03320312e-02,  1.06933594e-01,  6.83593750e-02, -1.00708008e-02,
       -1.04492188e-01, -7.95898438e-02, -2.69775391e-02,  7.61718750e-02,
        8.64257812e-02,  1.15722656e-01, -1.87500000e-01, -8.30078125e-02,
        1.69921875e-01, -1.49414062e-01, -1.49536133e-02,  4.63867188e-02,
        7.17773438e-02,  1.59179688e-01, -1.87988281e-02, -9.37500000e-02,
        1.07421875e-02, -1.51367188e-01,  2.04101562e-01, -1.58203125e-01,
        1.24511719e-02,  7.56835938e-02, -2.55584717e-04,  6.07910156e-02,
        1.67968750e-01,  1.00585938e-01, -1.96289062e-01, -1.36108398e-02,
        5.37109375e-02, -1.28936768e-03,  4.46777344e-02, -8.48388672e-03,
        8.15429688e-02, -2.23632812e-01, -8.39843750e-02,  4.45556641e-03,
       -2.63671875e-01,  1.34887695e-02, -3.22265625e-02, -1.03149414e-02,
       -9.03320312e-02, -1.31835938e-01, -2.10937500e-01,  3.49121094e-02,
       -2.23632812e-01, -2.49023438e-02,  9.81445312e-02,  4.37011719e-02,
        4.41894531e-02, -1.86523438e-01,  2.87109375e-01,  2.03125000e-01,
       -2.55859375e-01, -2.14843750e-01, -1.86523438e-01, -2.39257812e-01,
       -1.66015625e-02,  2.34375000e-02,  6.05468750e-02,  9.81445312e-02,
        2.04101562e-01,  6.93359375e-02, -2.96875000e-01, -8.93554688e-02,
        2.09045410e-03, -1.87500000e-01,  8.97216797e-03, -3.97949219e-02,
       -5.88378906e-02,  6.12792969e-02, -1.18652344e-01, -6.34765625e-02,
        1.80664062e-01, -5.93261719e-02, -2.03125000e-01,  5.39550781e-02,
       -6.64062500e-02,  1.67968750e-01,  5.98144531e-02,  1.62109375e-01,
       -1.24511719e-01,  1.83105469e-02,  1.29882812e-01, -6.25000000e-02,
        3.65234375e-01,  1.15722656e-01, -1.32812500e-01,  2.11914062e-01,
        3.00292969e-02, -9.17968750e-02, -5.17578125e-02, -2.08007812e-01,
       -6.68945312e-02,  1.75781250e-02, -1.41601562e-01, -1.96289062e-01,
        1.05468750e-01, -7.91015625e-02,  3.66210938e-03, -1.20117188e-01,
        1.81640625e-01,  6.25000000e-02, -8.49609375e-02,  1.69921875e-01,
        1.72851562e-01, -1.11816406e-01,  2.05078125e-01,  7.08007812e-02,
        5.27343750e-02, -3.80859375e-02,  3.93066406e-02,  1.37695312e-01,
       -2.12402344e-02,  1.25976562e-01,  2.14843750e-01,  1.88476562e-01,
        9.57031250e-02, -6.54296875e-02,  6.71386719e-04,  7.32421875e-02,
       -1.59263611e-04,  2.12890625e-01, -1.20239258e-02,  6.68945312e-02,
        1.14257812e-01,  6.78710938e-02, -1.62109375e-01,  5.32226562e-02,
       -1.43554688e-01,  1.56250000e-01,  1.01074219e-01,  1.15722656e-01,
        5.02929688e-02, -7.12890625e-02, -4.54101562e-02, -7.95898438e-02,
       -1.08886719e-01, -4.02832031e-02, -1.69921875e-01, -9.61914062e-02,
       -9.37500000e-02, -3.98437500e-01,  1.29882812e-01, -1.74804688e-01,
       -7.86132812e-02, -1.58203125e-01,  4.68750000e-02,  5.76171875e-02,
        6.64062500e-02,  1.14257812e-01, -1.50390625e-01,  1.15722656e-01,
        5.07812500e-02,  1.12304688e-01,  6.44531250e-02,  3.75976562e-02,
        1.10839844e-01, -2.34375000e-02, -4.76074219e-02,  2.62451172e-02,
       -2.19726562e-02, -1.88476562e-01,  5.63964844e-02, -3.02734375e-01,
       -1.68945312e-01,  1.84326172e-02,  1.04003906e-01,  9.03320312e-02],
      dtype=float32)

In [32]:
le = LabelEncoder()
df['airline_sentiment'] = le.fit_transform(df['airline_sentiment'])
df
# positive = 2, neutral = 1, negative = 0

                                                    text  airline_sentiment
0      [0.0652771, -0.025177002, 0.15722656, -0.00170...                  1
1      [0.025238037, -0.0074768066, -0.0210495, 0.082...                  2
2      [-0.01674028, 0.032792524, 0.059326172, 0.0763...                  1
3      [0.018322945, 0.063874125, 0.012535095, 0.0904...                  0
4      [0.102321625, 0.011981487, 0.059326172, 0.0765...                  0
...                                                  ...                ...
14635  [-0.020568848, 0.014526367, -0.010360718, 0.17...                  2
14636  [0.009950183, 0.025126139, 0.02629162, 0.04133...                  0
14637  [-0.016540527, -0.0063476562, 0.08666992, 0.18...                  1
14638  [0.016659824, -0.010292747, 0.046623923, 0.160...                  0
14639  [0.04509656, -0.0059667127, 0.050232198, 0.078...                  1

[14640 rows x 2 columns]

In [33]:
x = df['text']
y = df['airline_sentiment']

In [34]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [35]:
x_train.shape

(11712,)

In [36]:
log = LogisticRegression(verbose = 3)
log.fit(x_train.tolist(), y_train)

[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    2.3s finished

LogisticRegression(verbose=3)

In [37]:
y_pred = log.predict(x_test.tolist())
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.787568306010929

In [38]:
def predict_message_class(model, w2vmodel, message):
    message = clean_text(message)
    message_vector = avg_word2vec(message, w2vmodel)
    prediction = model.predict([message_vector])
    return prediction[0]

In [41]:
text1 = "Had a smooth flight with JetBlue. Loved the snacks and friendly staff!"
predict_message_class(log,model,text1)

2

In [48]:
text2 = "Checking in for my flight with United now. Boarding starts in an hour."
predict_message_class(log,model,text2)

0

In [45]:
text3 = "Terrible experience with Spirit Airlines — lost my luggage and rude staff."
predict_message_class(log,model,text3)

0